#!/usr/bin/env python3

import subprocess
import socket
import sys
import os
import json
import datetime

# Create a UDS socket
sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
server_address = '/var/run/user/1000/leftwm/leftwm.sock'
sock.connect(server_address)

def read_socket():
    try:
        data = sock.recv(1024)
        return json.loads(data)
    except json.decoder.JSONDecodeError as err:
        return None

def time():
    return datetime.datetime.now().strftime("%B %d, %Y  %I:%M:%S %p")

def format(data):
    return '%{{r}}{}\n'.format( time() )

bar = subprocess.Popen(['lemonbar', '-F#FFFFFFFF', '-B#FF222222', '-b', '-p'], 
                       stdin=subprocess.PIPE,
                       stdout=subprocess.DEVNULL,
                       stderr=subprocess.DEVNULL,
                       bufsize=1,
                       universal_newlines=True)

while True:
    data = read_socket()
    if data != None:
        formated = format(data)
        bar.stdin.write(formated)
        print( formated )



