#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#boot compton if it exists
if [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
fi

if [ -x "$(command -v lemonbar)" ]; then
  pkill lemonbar
  $SCRIPTPATH/pipe_status_to_lemonbar &
fi

