name: Run Nix Flake Build

on:
  workflow_call:

jobs:
  nix-flake:
    name: Nix Flake
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org

      - name: Nix flake check
        run: nix flake check

      - name: Nix build
        run: nix build
